# Validate protobuf files for incompatible changes.

name: Validate protobuf files

on:
  pull_request:
    paths:
      - 'proto/backend.proto'
    branches:
      - 'main'

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # Run `git checkout`
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false
      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@a47c93e0b1648d5651a065437926377d060baa99 # v1.50.0
      # Perform breaking change detection against the `proto` directory in the `main` branch
      - uses: bufbuild/buf-breaking-action@c57b3d842a5c3f3b454756ef65305a50a587c5ba # v1.1.4
        with:
          input: 'proto'
          against: 'https://github.com/grafana/grafana-plugin-sdk-go.git#branch=main,subdir=proto'
